### ISSUE TITLE
Example of @FlutterApi() would round this out

### ISSUE THREAD

**Issue by kjeremy** [gaaclarke/pigeon_plugin_example#2]
This project really helped me understand how to wire everything up. One thing that's missing is the other direction: namely calling a pigeon created FlutterApi from native code.

**Comment by gaaclarke** [comment]
There's an example of @FlutterApi here: https://github.com/flutter/samples/tree/master/add_to_app/books  Sorry if it's confusing to have to look at 2 different places for samples.  It wasn't my idea =)

**Comment by kjeremy** [comment]
In that example  (https://github.com/flutter/samples/blob/5adf66ba65fe3f78ae8a9bd1b228f0082fe76d04/add_to_app/books/android_books/app/src/main/java/dev/flutter/example/books/FlutterBookActivity.kt#L77) you're using `flutterEngine.dartExecutor`. For a plugin should that be `FlutterPluginBinding.getBinaryMessenger()` or do we need to create a new messenger for java -> dart?

**Comment by gaaclarke** [comment]
Yep, use `FlutterPluginBinding.getBinaryMessenger()`.

**Comment by gaaclarke** [comment]
I should have mentioned that there are some tiny nuances between add-to-app versus plugins.
