### ISSUE TITLE
Missing NSObjectProtocol per Pigeon v1.0.x

### ISSUE THREAD

**Issue by orenagiv** [gaaclarke/pigeon_plugin_example#3]
Hey @gaaclarke,

Per Pigeon v1.0.x I think that this line:
```let api : FLTExampleApi = SwiftPigeonPlugin.init()```
Needs to be added with the NSObjectProtocol:
```let api : FLTExampleApi & NSObjectProtocol = SwiftPigeonPlugin.init()```

https://github.com/gaaclarke/pigeon_plugin_example/blob/f729b969a087ee8c883c81051a24a03f6e3886e6/ios/Classes/SwiftPigeonPlugin.swift#L7

**Comment by gaaclarke** [comment]
Thanks, I'll give it a look.  I haven't had a chance to upgrade all the examples yet.

**Comment by gaaclarke** [comment]
Thanks, fixed it in https://github.com/gaaclarke/pigeon_plugin_example/commit/3d392c1985ce0bed2e435ae9c652f2deb2154639

**Comment by orenagiv** [comment]
Thx! 🙏
